export const users = [
  {
    character_img: "./aang.webp",
    name: "Aang",
    hair: "None",
    gender: "Male",
    nation: "Air",
    fighting: "All Elements",
    bending: true,
    book: "1: The Boy in the Iceberg",
    position: "Avatar",
    age: "121-140",
    hint: "The story's main character",
  },

  {
    character_img: "zuko.webp",
    name: "Zuko",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "1: The Boy in the Iceberg",
    position: "Royal Family",
    age: "1-20",
    hint: "Prince of Fire Nation",
  },

  {
    character_img: "katara.webp",
    name: "Katara",
    hair: "Brown",
    gender: "Female",
    nation: "Water",
    fighting: "Water Bending",
    bending: true,
    book: "1: The Boy in the Iceberg",
    position: "Team Avatar",
    age: "1-20",
    hint: "Avatar's love interest",
  },
  {
    character_img: "toph.webp",
    name: "Toph",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "2: The Swamp",
    position: "Team Avatar",
    age: "1-20",
    hint: "The blind girl on Team Avatar",
  },
  {
    character_img: "azula.webp",
    name: "Azula",
    hair: "Black",
    gender: "Female",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "1: The Storm",
    position: "Royal Family",
    age: "1-20",
    hint: "Zuko's crazy sister",
  },
  {
    character_img: "sokka.webp",
    name: "Sokka",
    hair: "Brown",
    gender: "Male",
    nation: "Water",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: The Boy in the Iceberg",
    position: "Team Avatar",
    age: "1-20",
    hint: "His favorite weapon is the boomerang",
  },
  {
    character_img: "iroh.webp",
    name: "Iroh",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "1: The Boy in the Iceberg",
    position: "Military",
    age: "41-60",
    hint: "Zuko's mentor",
  },
  {
    character_img: "ozai.webp",
    name: "Ozai",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "Part 2: Avatar Roku",
    position: "Royal Family",
    age: "41-60",
    hint: "Zuko's Father",
  },
  {
    character_img: "mai.webp",
    name: "Mai",
    hair: "Black",
    gender: "Female",
    nation: "Fire",
    fighting: "Melee Weapon",
    bending: false,
    book: "2: Return to Omashu",
    position: "Team Azula",
    age: "1-20",
    hint: "Impassive girl on Team Azula",
  },
  {
    character_img: "tylee.webp",
    name: "Ty Lee",
    hair: "Brown",
    gender: "Female",
    nation: "Fire",
    fighting: "Melee Weapon",
    bending: false,
    book: "2: Return to Omashu",
    position: "Team Azula",
    age: "1-20",
    hint: "Azula's teamate with 6 identical sisters",
  },
  {
    character_img: "roku.webp",
    name: "Roku",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "All Elements",
    bending: true,
    book: "1: Winter Solstice, Part 1: The Spirit World",
    age: "Dead",
    position: "Avatar",
    hint: "The Fire Nation born Avatar",
  },

  {
    character_img: "suki.webp",
    name: "Suki",
    hair: "Brown",
    gender: "Female",
    nation: "Earth",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: The Warriors of Kyoshi",
    age: "1-20",
    position: "Kyoshi Warrior",
    hint: "Kyoshi Warrior that liked Sokka",
  },
  {
    character_img: "theboulder.webp",
    name: "The Boulder",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "2: The Blind Bandit",
    age: "1-20",
    position: "Earth Rumble",
    hint: "Fought Toph in Earth Rumble Tournament",
  },

  {
    character_img: "tyro.webp",
    name: "Tyro",
    hair: "white",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "1: Imprisoned",
    age: "1-20",
    position: "Leader",
    hint: "Avatar helped this character move coal",
  },

  {
    character_img: "jet.webp",
    name: "Jet",
    hair: "Brown",
    gender: "Male",
    nation: "Earth",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: Jet",
    age: "1-20",
    position: "Freedom Fighter",
    hint: "Was the Leader of the Freedom Fighters",
  },
  {
    character_img: "bumi.webp",
    name: "Bumi",
    hair: "White",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "1: The King of Omashu",
    age: "81-100",
    position: "Leader",
    hint: "King of Omashu and Aang's childhood friend",
  },
  {
    character_img: "zhao.webp",
    name: "Zhao",
    hair: "Brown",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "1: The Southern Air Temple",
    age: "21-40",
    position: "Military",
    hint: "Set off to capture Avatar Aang before Zuko",
  },
  {
    character_img: "longfeng.webp",
    name: "Long Feng",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "2: City of Walls and Secrets",
    age: "21-40",
    position: "Leader",
    hint: "Captured Avatar Aang bison",
  },
  {
    character_img: "yue.webp",
    name: "Yue",
    hair: "White",
    gender: "Female",
    nation: "Water",
    fighting: "Water Bending",
    bending: true,
    book: "1: The Waterbending Master",
    age: "21-40",
    position: "Moon Spirit",
    hint: "Was Sokka's Girlfriend",
  },
  {
    character_img: "sozin.webp",
    name: "Sozin",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Avatar and the Fire Lord",
    age: "61-80",
    position: "Royal Family",
    hint: "Was close friends with Roku",
  },
  {
    character_img: "shirshu.webp",
    name: "June",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: Bato of the Water Tribe",
    age: "1-20",
    position: "Assasin",
    hint: "She was a bounty hunter that rode a shirshu",
  },

  {
    character_img: "kyoshi.webp",
    name: "Kyoshi",
    hair: "Brown",
    gender: "Female",
    nation: "Earth",
    fighting: "Earth",
    bending: false,
    book: "2: The Avatar State",
    age: "Dead",
    position: "Avatar",
    hint: "The Earth Kingdom Avatar that was capable of lavabending",
  },
  {
    character_img: "smellerbee.webp",
    name: "Smellerbee",
    hair: "Brown",
    gender: "Female",
    nation: "Earth",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: Jet",
    age: "1-20",
    position: "Freedom Fighter",
    hint: "The member of Freedom Fighter that dressed tomboyish",
  },
  {
    character_img: "chong.webp",
    name: "Chong",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: The Cave of Two Lovers",
    age: "21-40",
    position: "Nomad",
    hint: "Free-spirited, carefree nomad. Leads his group of traveling musicians and famously sings the Secret Tunnel",
  },
  {
    character_img: "kuei.webp",
    name: "Kuei",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: City of Walls and Secrets",
    age: "21-40",
    position: "Government",
    hint: "The 52nd Earth King",
  },

  {
    character_img: "piandao.webp",
    name: "Piandao",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Melee Weapon",
    bending: false,
    book: "3",
    age: "21-40",
    position: "White Lotus",
    hint: "Swords Master that taught Sokka",
  },

  {
    character_img: "teo.webp",
    name: "Teo",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "1: The Northern Air Temple",
    age: "1-20",
    position: "Air Glider",
    hint: "The Mechanist Son who air glides",
  },

  {
    character_img: "jin.webp",
    name: "Jin",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: The Tales of Ba Sing Se",
    age: "1-20",
    position: "Refugee",
    hint: "Zuko's date",
  },
  {
    character_img: "hahn.webp",
    name: "Hahn",
    hair: "Black",
    gender: "Male",
    nation: "Water",
    fighting: "Passive",
    bending: false,
    book: "2: The Siege of the North, Part 1",
    age: "1-20",
    position: "Warrior",
    hint: "Had arranged marriage with Princess Yue",
  },

  {
    character_img: "onji.webp",
    name: "On Ji",
    hair: "Brown",
    gender: "Female",
    nation: "Fire",
    fighting: "Passive",
    bending: false,
    book: "3: The Headband",
    age: "1-20",
    position: "Fire Nation School",
    hint: "Aang's dance partner",
  },

  {
    character_img: "meng.webp",
    name: "Meng",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "1: The Fortuneteller",
    age: "1-20",
    position: "Aunt Wu Salon",
    hint: "Love interest is Aang",
  },

  {
    character_img: "kuruk.webp",
    name: "Kuruk",
    hair: "Black",
    gender: "Male",
    nation: "Water",
    fighting: "All Elements",
    bending: true,
    book: "2: The Avatar State",
    age: "Dead",
    position: "Avatar",
    hint: "Fought Spirits as Avatar",
  },

  {
    character_img: "pipsqueak.webp",
    name: "Pipsqueak",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: Jet",
    age: "1-20",
    position: "Freedom Fighter",
    hint: "Strongest member physically of Freedom Fighters",
  },
  {
    character_img: "chan.webp",
    name: "Chan",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Passive",
    bending: false,
    book: "3: The Beach",
    age: "1-20",
    position: "Ember Island",
    hint: "Azula flirts with this person",
  },
  {
    character_img: "haru.webp",
    name: "Haru",
    hair: "Brown",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth",
    bending: true,
    book: "1: Imprisoned",
    age: "21-40",
    position: "Prisoner",
    hint: "Avoids earthbending in fear of fire nation",
  },

  {
    character_img: "hama.webp",
    name: "Hama",
    hair: "White",
    gender: "Female",
    nation: "Water",
    fighting: "Water",
    bending: true,
    book: "3: The Puppetmaster",
    age: "61-80",
    position: "Prisoner",
    hint: "Inventor of bloodbending",
  },

  {
    character_img: "pakku.webp",
    name: "Pakku",
    hair: "White",
    gender: "Male",
    nation: "Water",
    fighting: "Water",
    bending: true,
    book: "1: The Waterbending Master",
    age: "61-80",
    position: "Master",
    hint: "Katara's waterbending master",
  },

  {
    character_img: "oyaji.webp",
    name: "Oyaji",
    hair: "White",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "1: The Warriors of Kyoshi",
    age: "61-80",
    position: "Kyoshi Warrior",
    hint: "Leader of Kyoshi Island who thought the Avatar was Fire Nation Spies",
  },

  {
    character_img: "how.webp",
    name: "How",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth",
    bending: true,
    book: "2: The Earth King",
    age: "21-40",
    position: "Government",
    hint: "Hi ranking military leader in Earth Kingdom who guards the Outer Wall of Ba Sing Se",
  },
  {
    character_img: "sung.webp",
    name: "Sung",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth",
    bending: true,
    book: "2: The Drill",
    age: "21-40",
    position: "Government",
    hint: "Lazy commanding skills",
  },

  {
    character_img: "quon.webp",
    name: "Quon",
    hair: "None",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: Lake Laogai",
    age: "21-40",
    position: "Business Man",
    hint: "Made good business selling tea",
  },

  {
    character_img: "tycho.webp",
    name: "Tycho",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Melee Weapon",
    bending: true,
    book: "2: City of Walls and Secrets",
    age: "21-40",
    position: "Runt",
    hint: "Did not get funded to go to University",
  },

  {
    character_img: "hakoda.webp",
    name: "Hakoda",
    hair: "Brown",
    gender: "Male",
    nation: "Water",
    fighting: "Melee Weapon",
    bending: true,
    book: "1: Bato of the Water Tribe",
    age: "21-40",
    position: "Warrior",
    hint: "Sokka's Father",
  },

  {
    character_img: "joodee.webp",
    name: "Joo Dee",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: City of Walls and Secrets",
    age: "21-40",
    position: "Government",
    hint: "Robotic and creepy voice",
  },

  {
    character_img: "kanna.webp",
    name: "Kanna",
    hair: "white",
    gender: "Female",
    nation: "Water",
    fighting: "Passive",
    bending: true,
    book: "1: The Boy in the IceBerg",
    age: "61-80",
    position: "Tribe Elder",
    hint: "Referred to by Gran Gran",
  },
  {
    character_img: "gyatso.webp",
    name: "Gyatso",
    hair: "None",
    gender: "Male",
    nation: "Air",
    fighting: "Air Bending",
    bending: true,
    book: "1: The Southern Air Temple",
    age: "Dead",
    position: "Monk",
    hint: "Aang said he was the greatest airbending master",
  },
  {
    character_img: "sela.webp",
    name: "Sela",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: Zuko Alone",
    age: "21-40",
    position: "Village Resident",
    hint: "Gansu's wife who took care of Zuko in Earth Kingdom",
  },

  {
    character_img: "poon.webp",
    name: "Poon",
    hair: "Brown",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: Sokka's Master",
    age: "21-40",
    position: "Military",
    hint: "This character belittled iroh in prison ",
  },
  {
    character_img: "yagoda.webp",
    name: "Yagoda",
    hair: "White",
    gender: "Female",
    nation: "Water",
    fighting: "Water Bending",
    bending: true,
    book: "1: The Waterbending Master",
    age: "61-80",
    position: "Master",
    hint: "Was a waterbending master who taught healing from Agna Qel'a",
  },
  {
    character_img: "azulon.webp",
    name: "Azulon",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "2: Zuko Alone",
    age: "Dead",
    position: "Royal Family",
    hint: "First son of Fire Lord Sozin and killed by Zuko's mom",
  },

  {
    character_img: "jeong.webp",
    name: "Jeon Jeong",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "1: The Deserter",
    age: "61-80",
    position: "White Lotus",
    hint: "Left the fire nation and taught Aang firebending",
  },

  {
    character_img: "ming.webp",
    name: "Ming",
    hair: "Brown",
    gender: "Female",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Day of Black Sun, Part 1: The Invasion",
    age: "1-20",
    position: "Military",
    hint: "Was kind to Iroh as a Prison Guard",
  },

  {
    character_img: "jee.webp",
    name: "Jee",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "1: The Waterbending Scroll",
    age: "41-60",
    position: "Military",
    hint: "Lieutenant who hunted Avatar Aang alongside Zuko",
  },

  {
    character_img: "moku.webp",
    name: "Moku",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: "None",
    book: "2: The Cave of Two Lovers",
    age: "21-40",
    position: "Nomad",
    hint: "Nomad who played hand drum and traveled with Chong",
  },

  {
    character_img: "gansu.webp",
    name: "Gansu",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: "None",
    book: "2: Zuko Alone",
    age: "21-40",
    position: "Village Resident",
    hint: "Zuko helped fix this character's barn",
  },

  {
    character_img: "kwan.webp",
    name: "Kwan",
    hair: "Brown",
    gender: "Female",
    nation: "Fire",
    fighting: "Passive",
    bending: "None",
    book: "3: The Headband",
    age: "21-40",
    position: "Instructor",
    hint: "Teacher who made mockery of Aang",
  },

  {
    character_img: "luten.webp",
    name: "Lu Ten",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Passive",
    bending: "None",
    book: "2: Bitter Work",
    age: "Dead",
    position: "Military",
    hint: "Died in Siege of Ba Sing Se",
  },

  {
    character_img: "fung.webp",
    name: "Fung",
    hair: "None",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: "None",
    book: "2: The Dessert",
    age: "61-80",
    position: "White Lotus",
    hint: "Owned a flower shop that was secretly White Lotus meeting place",
  },

  {
    character_img: "combustion.webp",
    name: "Combustion Man",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Headband",
    age: "21-40",
    position: "Assasin",
    hint: "Shot his powers from his forehead",
  },

  {
    character_img: "fong.webp",
    name: "Fong",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "2: The Avatar State",
    age: "21-40",
    position: "Military",
    hint: "Earth Kingdom General who tried to trigger the Avatar State",
  },

  {
    character_img: "mechanist.webp",
    name: "Mechanist",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: "None",
    book: "1: The Northern Air Temple",
    age: "41-60",
    position: "Inventor",
    hint: "Was an inventor who helped Avatar invade Fire Nation ",
  },

  {
    character_img: "zei.webp",
    name: "Zei",
    hair: "Brown",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: "None",
    book: "210: The Library",
    age: "21-40",
    position: "Teacher",
    hint: "Was an eccentric anthropologist who traveled the world",
  },

  {
    character_img: "longshot.webp",
    name: "Longshot",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Ranged Weapon",
    bending: "None",
    book: "1: Jet",
    age: "1-20",
    position: "Freedom Fighters",
    hint: "Very skilled archer who was apart of the Freedom Fighters",
  },

  {
    character_img: "hide.webp",
    name: "Hide",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Headband",
    age: "1-20",
    position: "Fire Nation School",
    hint: "Fought Aang during Fire Nation School",
  },

  {
    character_img: "ruonjian.webp",
    name: "Ruon-Jian",
    hair: "Brown",
    gender: "Male",
    nation: "Fire",
    fighting: "Passive",
    bending: false,
    book: "3: The Beach",
    age: "1-20",
    position: "Ember Island",
    hint: "Teenage boy on Ember Island who liked Mai",
  },

  {
    character_img: "lee.webp",
    name: "Lee",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: Zuko Alone",
    age: "1-20",
    position: "Village Resident",
    hint: "Boy who invited Zuko over to his house to repay him",
  },

  {
    character_img: "qin.webp",
    name: "Qin",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Passive",
    bending: false,
    book: "2: The Northern Air Temple",
    age: "61-80",
    position: "Military",
    hint: "Oversaw the Fire Nation military and used the mechanist's inventions",
  },

  {
    character_img: "chit.webp",
    name: "Chit Sang",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Boiling Rock, Part 1",
    age: "21-40",
    position: "Prisoner",
    hint: "Helped Sokka escape while in the Cooler",
  },

  {
    character_img: "ursa.webp",
    name: "Ursa",
    hair: "Brown",
    gender: "Female",
    nation: "Fire",
    fighting: "Passive",
    bending: "None",
    book: "207: Zuko Alone",
    age: "21-40",
    position: "Royal Family",
    hint: "Protected her son Zuko by poisening Azulon",
  },

  {
    character_img: "tachi.webp",
    name: "Tashi",
    hair: "None",
    gender: "Male",
    nation: "Air",
    fighting: "Air Bending",
    bending: true,
    book: "1: The Southern Air Temple",
    age: "Dead",
    position: "Monk",
    hint: "One of the monks in charage of Southern Air Temple",
  },

  {
    character_img: "exan.webp",
    name: "Mung",
    hair: "Black",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Painted Lady",
    age: "21-40",
    position: "Military",
    hint: "One of the Fire Nation Generals who were rutheless",
  },

  {
    character_img: "bato.webp",
    name: "Bato",
    hair: "Black",
    gender: "Male",
    nation: "Water",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: Bato of the Water Tribe",
    age: "21-40",
    position: "Warrior",
    hint: "One of Hakoda's friends and took care of Sokka and Katara",
  },

  {
    character_img: "lao.webp",
    name: "Lao Beifong",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: The Blind Bandit",
    age: "41-60",
    position: "Business Man",
    hint: "Toph's Father who was strict",
  },
  {
    character_img: "ying.webp",
    name: "Ying",
    hair: "Black",
    gender: "Female",
    nation: "Earth",
    fighting: "Passive",
    bending: false,
    book: "2: Zuko Alone",
    age: "21-40",
    position: "Village Resident",
    hint: "Traveled with Avatar through the Full Moon Bay",
  },

  {
    character_img: "gow.webp",
    name: "Gow",
    hair: "Black",
    gender: "Male",
    nation: "Earth",
    fighting: "Earth Bending",
    bending: true,
    book: "2: Zuko Alone",
    age: "21-40",
    position: "Military",
    hint: "Accused Zuko of throwing rock at him and they fought",
  },

  {
    character_img: "loandli.webp",
    name: "Lo and Li",
    hair: "White",
    gender: "Female",
    nation: "Fire",
    fighting: "Passive",
    bending: false,
    book: "2: The Avatar State",
    age: "61-80",
    position: "Instructor",
    hint: "Were the mentors of Azula",
  },
  {
    character_img: "yonrha.webp",
    name: "Yon Rha",
    hair: "White",
    gender: "Male",
    nation: "Fire",
    fighting: "Fire Bending",
    bending: true,
    book: "3: The Southern Raiders",
    age: "41-60",
    position: "Military",
    hint: "Killed Katara's mother",
  },
  {
    character_img: "arnook.webp",
    name: "Arnook",
    hair: "Black",
    gender: "Male",
    nation: "Water",
    fighting: "Melee Weapon",
    bending: false,
    book: "1: The Waterbending Master",
    age: "41-60",
    position: "Leader",
    hint: "Father of Princess Yue",
  },
];
